### ISSUE TITLE
Git LFS

### ISSUE THREAD

**Issue by chrissexton** [IUS-CS/s22-project-breakneck#17]
Hi all,

You're using Git LFS to store at least a large file. While I don't mind if you do and we should use the resources, this is one that is shared amongst all 1600 repositories so we have to be a bit careful. In addition, I'm a bit concerned that you won't have enough bandwidth allotment for the feature to work for you anyway. Regardless of how it shakes out, I'd probably need to remove the assets after the course is over in case somebody else uses the feature in the future.

Would you put some thought into a secondary storage solution for those assets? As long as they're accessible in some public means, it should be fine. Probably create a script in your repository to pull them down from a third-party service.

Please reply to this issue and let me know what your plan is.

<img width="938" alt="image" src="https://user-images.githubusercontent.com/3216719/157657746-2e526286-4d49-4228-9d3c-3c59d4ccb08e.png">

**Comment by zh1322114772** [comment]
we found a third-party storge system, will move models soon
